// Builtin token defaults — the single source of truth, consumed by both
// Services/Theme.qml (QML import) and bin/theme-apply (eval). A theme file
// overrides per-key; anything it omits resolves to these values everywhere,
// so the shell and every templated app agree on the fallback.
var THEME_DEFAULTS = {
  "meta.mode": "dark",
  "meta.preset": "flat",
  "surface.0": "#16161e",
  "surface.1": "#1a1b26",
  "surface.2": "#24283b",
  "surface.3": "#2f3549",
  "text.primary": "#c0caf5",
  "text.muted": "#58618c",
  "text.inverse": "#15161e",
  "text.on-accent": "#15161e",
  "accent.accent": "#7aa2f7",
  "accent.error": "#f7768e",
  "accent.warn": "#e0af68",
  "accent.ok": "#9ece6a",
  "ansi.black": "#15161e",
  "ansi.red": "#f7768e",
  "ansi.green": "#9ece6a",
  "ansi.yellow": "#e0af68",
  "ansi.blue": "#7aa2f7",
  "ansi.magenta": "#bb9af7",
  "ansi.cyan": "#7dcfff",
  "ansi.white": "#a9b1d6",
  "ansi.bright-black": "#414868",
  "ansi.bright-red": "#ff7a93",
  "ansi.bright-green": "#b9f27c",
  "ansi.bright-yellow": "#ff9e64",
  "ansi.bright-blue": "#7da6ff",
  "ansi.bright-magenta": "#bb9af7",
  "ansi.bright-cyan": "#0db9d7",
  "ansi.bright-white": "#c0caf5",
  "shape.radius": 8,
  "shape.border-width": 1,
  "space.unit": 4,
  "space.density": 1.0,
  "font.ui": "Maple Mono",
  "font.mono": "Maple Mono",
  "font.size": 12,
  "motion.duration": 150,
  "motion.easing": "standard",
  // Compositor motion (templates/niri-theme.kdl.tmpl via niri_animations).
  // Curve names resolve in the emitter; see Commons/presets.js.
  "motion.open-ms": 400,
  "motion.open-curve": "signature",
  "motion.close-ms": 150,
  "motion.close-curve": "linear",
  "motion.spring-damping": 1.0,
  "motion.spring-stiffness": 1000,
  "motion.workspace-stiffness": 1200,
  // Compositor blur (Services/Blur.qml renders the niri fragment from
  // these; `enabled` is only the theme DEFAULT — the blur flag file, when
  // it holds on/off, is the user override that wins across theme switches).
  "blur.enabled": "false",
  "blur.alpha": 0.8,
  "blur.noise": 0.02,
  "blur.saturation": 1.5,
  // Window opacity pairs: base (blur off) and frost (blur on). Emitted by
  // niri_opacity / the blur fragment; media apps are re-exempted after.
  "opacity.active": 0.985,
  "opacity.inactive": 0.96,
  "opacity.blur-active": 0.95,
  "opacity.blur-inactive": 0.9,
  // Window drop shadow (layout.shadow in the niri include).
  "shadow.enabled": "false",
  "shadow.softness": 30,
  "shadow.spread": 5,
  "shadow.offset-x": 0,
  "shadow.offset-y": 5,
  "shadow.color": "#00000077",
  "bar.height": 26,
  "bar.width-vertical": 28
}
