// Builtin token defaults — the single source of truth, consumed by both
// Services/Theme.qml (QML import) and bin/theme-apply (eval). A theme file
// overrides per-key; anything it omits resolves to these values everywhere,
// so the shell and every templated app agree on the fallback.
var THEME_DEFAULTS = {
  "meta.mode": "dark",
  "surface.0": "#16161e",
  "surface.1": "#1a1b26",
  "surface.2": "#24283b",
  "surface.3": "#2f3549",
  "text.primary": "#c0caf5",
  "text.muted": "#58618c",
  "text.inverse": "#15161e",
  "text.on-accent": "#15161e",
  "accent.accent": "#7aa2f7",
  "accent.error": "#f7768e",
  "accent.warn": "#e0af68",
  "accent.ok": "#9ece6a",
  "ansi.black": "#15161e",
  "ansi.red": "#f7768e",
  "ansi.green": "#9ece6a",
  "ansi.yellow": "#e0af68",
  "ansi.blue": "#7aa2f7",
  "ansi.magenta": "#bb9af7",
  "ansi.cyan": "#7dcfff",
  "ansi.white": "#a9b1d6",
  "ansi.bright-black": "#414868",
  "ansi.bright-red": "#ff7a93",
  "ansi.bright-green": "#b9f27c",
  "ansi.bright-yellow": "#ff9e64",
  "ansi.bright-blue": "#7da6ff",
  "ansi.bright-magenta": "#bb9af7",
  "ansi.bright-cyan": "#0db9d7",
  "ansi.bright-white": "#c0caf5",
  "shape.radius": 8,
  "shape.border-width": 1,
  "space.unit": 4,
  "space.density": 1.0,
  "font.ui": "Maple Mono",
  "font.mono": "Maple Mono",
  "font.size": 12,
  "motion.duration": 150,
  "motion.easing": "standard",
  "bar.height": 26,
  "bar.width-vertical": 28
}
