# Fuzzel theme colors - Generated by theme script
[colors]
background={{ background_strip }}f0
text={{ foreground_strip }}ff
prompt={{ foreground_strip }}cc
input={{ foreground_strip }}ff
match={{ accent_strip }}ff
selection={{ accent_strip }}ff
selection-text={{ background_strip }}ff
selection-match={{ background_strip }}ff
border={{ accent_strip }}ff
