# FZF theme colors - generated by theme script
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
    --color=bg+:{{ color8 }},spinner:{{ accent }},hl:{{ color1 }} \
    --color=fg:{{ foreground }},header:{{ color1 }},info:{{ color5 }} \
    --color=pointer:{{ accent }},marker:{{ accent }},prompt:{{ color5 }} \
    --color=hl+:{{ color1 }}"
