# generated by theme-apply — do not edit
#
# Ported from omarchy's default/themed/kitty.conf.tpl (their theme system
# renders the same file into ~/.local/state/omarchy/current/theme/kitty.conf).
# Their key list is kept as-is; the token bindings follow foot-theme.ini.tmpl
# instead of omarchy's own, because the two terminals on this desktop must
# render one palette: omarchy maps color0/color7 to background/foreground,
# while this theme schema carries real ansi.black / ansi.white and foot uses
# them. Dropped from their file: active_tab_background — the tab bar is
# hidden, so it can never draw.
foreground {{text.primary}}
background {{surface.0}}
selection_foreground {{text.primary}}
selection_background {{surface.3}}

cursor {{ansi.bright-white}}
cursor_text_color {{surface.0}}

url_color {{accent.accent}}
active_border_color {{accent.accent}}

color0 {{ansi.black}}
color1 {{ansi.red}}
color2 {{ansi.green}}
color3 {{ansi.yellow}}
color4 {{ansi.blue}}
color5 {{ansi.magenta}}
color6 {{ansi.cyan}}
color7 {{ansi.white}}
color8 {{ansi.bright-black}}
color9 {{ansi.bright-red}}
color10 {{ansi.bright-green}}
color11 {{ansi.bright-yellow}}
color12 {{ansi.bright-blue}}
color13 {{ansi.bright-magenta}}
color14 {{ansi.bright-cyan}}
color15 {{ansi.bright-white}}
