# Lazygit configuration - generated by bin/theme
# Do not edit manually

gui:
  showIcons: true
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "{{ accent }}"
      - bold
    inactiveBorderColor:
      - "{{ color8 }}"
    optionsTextColor:
      - "{{ accent }}"
    selectedLineBgColor:
      - "{{ color0 }}"
    selectedRangeBgColor:
      - "{{ color0 }}"
    cherryPickedCommitBgColor:
      - "{{ color6 }}"
    cherryPickedCommitFgColor:
      - "{{ background }}"
    unstagedChangesColor:
      - "{{ color1 }}"
    defaultFgColor:
      - "{{ foreground }}"
    searchingActiveBorderColor:
      - "{{ color3 }}"

git:
  paging:
    colorArg: always
    pager: delta --paging=never

  pull:
    mode: rebase

os:
  editPreset: nvim
