// Niri Theme Colors
// Generated by theme script - do not edit directly

layout {
    focus-ring {
        active-color "{{ accent }}"
        inactive-color "{{ color8 }}"
    }

    border {
        active-color "{{ accent }}"
        inactive-color "{{ color8 }}"
    }
}
