# generated by theme-apply — do not edit (ported 2026-08-07 from the old
# dotfiles-linux yazi-theme template onto the current token schema)

[mgr]
cwd = { fg = "{{accent.accent}}" }
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "{{ansi.yellow}}", bold = true, italic = true, underline = true }
find_position = { fg = "{{ansi.magenta}}", bg = "reset", italic = true }

# Marker
marker_copied = { fg = "{{ansi.green}}", bg = "{{ansi.green}}" }
marker_cut = { fg = "{{ansi.red}}", bg = "{{ansi.red}}" }
marker_selected = { fg = "{{accent.accent}}", bg = "{{accent.accent}}" }

# Tab
tab_active = { fg = "{{surface.0}}", bg = "{{accent.accent}}" }
tab_inactive = { fg = "{{text.primary}}", bg = "{{ansi.black}}" }
tab_width = 1

# Count
count_copied = { fg = "{{surface.0}}", bg = "{{ansi.green}}" }
count_cut = { fg = "{{surface.0}}", bg = "{{ansi.red}}" }
count_selected = { fg = "{{surface.0}}", bg = "{{accent.accent}}" }

# Border
border_symbol = "│"
border_style = { fg = "{{ansi.black}}" }

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "{{ansi.black}}", bg = "{{ansi.black}}" }

# Mode
mode_normal = { fg = "{{surface.0}}", bg = "{{accent.accent}}", bold = true }
mode_select = { fg = "{{surface.0}}", bg = "{{ansi.green}}", bold = true }
mode_unset = { fg = "{{surface.0}}", bg = "{{ansi.magenta}}", bold = true }

# Progress
progress_label = { fg = "{{text.primary}}", bold = true }
progress_normal = { fg = "{{accent.accent}}", bg = "{{ansi.black}}" }
progress_error = { fg = "{{ansi.red}}", bg = "{{ansi.black}}" }

# Permissions
permissions_t = { fg = "{{accent.accent}}" }
permissions_r = { fg = "{{ansi.yellow}}" }
permissions_w = { fg = "{{ansi.red}}" }
permissions_x = { fg = "{{ansi.green}}" }
permissions_s = { fg = "{{ansi.bright-black}}" }

[pick]
border = { fg = "{{accent.accent}}" }
active = { fg = "{{ansi.magenta}}", bold = true }
inactive = {}

[input]
border = { fg = "{{accent.accent}}" }
title = {}
value = {}
selected = { reversed = true }

[confirm]
border = { fg = "{{accent.accent}}" }
title = { fg = "{{accent.accent}}" }
content = {}
list = {}
btn_yes = { reversed = true }
btn_no = {}
btn_labels = [ "  [Y]es  ", "  [N]o  " ]

[completion]
border = { fg = "{{accent.accent}}" }
active = { reversed = true }
inactive = {}
icon_file = ""
icon_folder = ""
icon_command = ""

[tasks]
border = { fg = "{{accent.accent}}" }
title = {}
hovered = { fg = "{{ansi.magenta}}" }

[which]
cols = 3
mask = { bg = "{{surface.0}}" }
cand = { fg = "{{accent.accent}}" }
rest = { fg = "{{ansi.bright-black}}" }
desc = { fg = "{{ansi.magenta}}" }
separator = "  "
separator_style = { fg = "{{ansi.black}}" }

[help]
on = { fg = "{{accent.accent}}" }
run = { fg = "{{ansi.magenta}}" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "{{text.primary}}", bg = "{{ansi.black}}" }

[notify]
title_info = { fg = "{{ansi.green}}" }
title_warn = { fg = "{{ansi.yellow}}" }
title_error = { fg = "{{ansi.red}}" }
icon_info = ""
icon_warn = ""
icon_error = ""

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "{{ansi.cyan}}" },

	# Media
	{ mime = "{audio,video}/*", fg = "{{ansi.magenta}}" },

	# Archives
	{ mime = "application/*zip*", fg = "{{ansi.red}}" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "{{ansi.red}}" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "{{ansi.blue}}" },

	# Fallback
	{ url = "*", fg = "{{text.primary}}" },
	{ url = "*/", fg = "{{accent.accent}}" },
]

[icon]
globs = []
dirs = []
files = []
exts = []
conds = []
