# generated by theme-apply — do not edit.
#
# Almost everything that used to live here now lives in the flavor rendered
# next to it (templates/yazi-flavor.toml.tmpl → flavors/qshell.yazi/), for one
# reason: only a flavor carries a tmTheme, and the tmTheme is what colours the
# code preview. yazi merges flavor.toml first and this file over the top, so
# anything set here still wins — it is the right place for preferences that
# are not palette, which is all that is left below.
#
# Both polarities name the same flavor because theme-apply re-renders it for
# whichever theme is active, rather than shipping a light and a dark copy. The
# two keys still matter: yazi picks between them from the terminal's reported
# background (OSC 11), so a light terminal and a dark one both resolve to a
# flavor that is already the right polarity.
[flavor]
dark = "qshell"
light = "qshell"

# Nerd-font icons are ON (user ask 2026-08-18), which here just means saying
# nothing: yazi ships the nvim-web-devicons set built in, and this file used to
# carry upstream's "hide all icons" recipe (FAQ: "I don't like nerd-fonts!") —
# five empty arrays that REPLACE that set rather than adding to it. It came
# across from the pre-2026 dotfiles-linux theme and had been suppressing every
# file icon since. Removing the block restores the whole set.
#
# Two things make this safe here that would not be elsewhere:
#
#   - The font. `font_family Maple Mono` has no PUA glyphs of its own, but
#     fontconfig falls back to Symbols Nerd Font for every codepoint yazi uses
#     (U+E5FF folder, U+F15B file, U+F498 Downloads, U+F489 exec — all checked
#     with `fc-match ':charset=…'`).
#   - kitty's icon-size bug (FAQ: "Why do my icons shrink in kitty, and enlarge
#     when scrolling?") needs the file list to carry an explicit foreground
#     colour, which the flavor's [filetype] fallback rules now give every row.
#     Upstream's own answer to that bug is "use a flavor", which is what we do.
#
# The icon colours are nvim-web-devicons' own (material-ish: #03a9f4 folders,
# #8bc34a executables), not palette tokens, so they do not track the theme.
# Recolouring them means overriding the whole set — see icons-brew.yazi in the
# resources list — and is deliberately not done.
