# Yazi theme - generated by Nova theme system
# Based on: https://yazi-rs.github.io/docs/configuration/theme

[mgr]
cwd = { fg = "{{ accent }}" }
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "{{ color3 }}", bold = true, italic = true, underline = true }
find_position = { fg = "{{ color5 }}", bg = "reset", italic = true }

# Marker
marker_copied = { fg = "{{ color2 }}", bg = "{{ color2 }}" }
marker_cut = { fg = "{{ color1 }}", bg = "{{ color1 }}" }
marker_selected = { fg = "{{ accent }}", bg = "{{ accent }}" }

# Tab
tab_active = { fg = "{{ background }}", bg = "{{ accent }}" }
tab_inactive = { fg = "{{ foreground }}", bg = "{{ color0 }}" }
tab_width = 1

# Count
count_copied = { fg = "{{ background }}", bg = "{{ color2 }}" }
count_cut = { fg = "{{ background }}", bg = "{{ color1 }}" }
count_selected = { fg = "{{ background }}", bg = "{{ accent }}" }

# Border
border_symbol = "│"
border_style = { fg = "{{ color0 }}" }

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "{{ color0 }}", bg = "{{ color0 }}" }

# Mode
mode_normal = { fg = "{{ background }}", bg = "{{ accent }}", bold = true }
mode_select = { fg = "{{ background }}", bg = "{{ color2 }}", bold = true }
mode_unset = { fg = "{{ background }}", bg = "{{ color5 }}", bold = true }

# Progress
progress_label = { fg = "{{ foreground }}", bold = true }
progress_normal = { fg = "{{ accent }}", bg = "{{ color0 }}" }
progress_error = { fg = "{{ color1 }}", bg = "{{ color0 }}" }

# Permissions
permissions_t = { fg = "{{ accent }}" }
permissions_r = { fg = "{{ color3 }}" }
permissions_w = { fg = "{{ color1 }}" }
permissions_x = { fg = "{{ color2 }}" }
permissions_s = { fg = "{{ color8 }}" }

[pick]
border = { fg = "{{ accent }}" }
active = { fg = "{{ color5 }}", bold = true }
inactive = {}

[input]
border = { fg = "{{ accent }}" }
title = {}
value = {}
selected = { reversed = true }

[confirm]
border = { fg = "{{ accent }}" }
title = { fg = "{{ accent }}" }
content = {}
list = {}
btn_yes = { reversed = true }
btn_no = {}
btn_labels = [ "  [Y]es  ", "  [N]o  " ]

[completion]
border = { fg = "{{ accent }}" }
active = { reversed = true }
inactive = {}
icon_file = ""
icon_folder = ""
icon_command = ""

[tasks]
border = { fg = "{{ accent }}" }
title = {}
hovered = { fg = "{{ color5 }}" }

[which]
cols = 3
mask = { bg = "{{ background }}" }
cand = { fg = "{{ accent }}" }
rest = { fg = "{{ color8 }}" }
desc = { fg = "{{ color5 }}" }
separator = "  "
separator_style = { fg = "{{ color0 }}" }

[help]
on = { fg = "{{ accent }}" }
run = { fg = "{{ color5 }}" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "{{ foreground }}", bg = "{{ color0 }}" }

[notify]
title_info = { fg = "{{ color2 }}" }
title_warn = { fg = "{{ color3 }}" }
title_error = { fg = "{{ color1 }}" }
icon_info = ""
icon_warn = ""
icon_error = ""

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "{{ color6 }}" },

	# Media
	{ mime = "{audio,video}/*", fg = "{{ color5 }}" },

	# Archives
	{ mime = "application/*zip*", fg = "{{ color1 }}" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "{{ color1 }}" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "{{ color4 }}" },

	# Fallback
	{ name = "*", fg = "{{ foreground }}" },
	{ name = "*/", fg = "{{ accent }}" },
]

[icon]
globs = []
dirs = []
files = []
exts = []
conds = []
