# gruvbox
# Converted from Helix theme

# Palette
declare-option str bg0 'rgb:282828'
declare-option str bg0_s 'rgb:32302f'
declare-option str bg1 'rgb:3c3836'
declare-option str bg2 'rgb:504945'
declare-option str bg3 'rgb:665c54'
declare-option str bg4 'rgb:7c6f64'
declare-option str fg0 'rgb:fbf1c7'
declare-option str fg1 'rgb:ebdbb2'
declare-option str fg2 'rgb:d5c4a1'
declare-option str fg3 'rgb:bdae93'
declare-option str fg4 'rgb:a89984'
declare-option str gray 'rgb:928374'
declare-option str red0 'rgb:cc241d'
declare-option str red1 'rgb:fb4934'
declare-option str green0 'rgb:98971a'
declare-option str green1 'rgb:b8bb26'
declare-option str yellow0 'rgb:d79921'
declare-option str yellow1 'rgb:fabd2f'
declare-option str blue0 'rgb:458588'
declare-option str blue1 'rgb:83a598'
declare-option str purple0 'rgb:b16286'
declare-option str purple1 'rgb:d3869b'
declare-option str aqua0 'rgb:689d6a'
declare-option str aqua1 'rgb:8ec07c'
declare-option str orange0 'rgb:d65d0e'
declare-option str orange1 'rgb:fe8019'

# Faces
set-face global Default default
set-face global LineNumbers "%opt{bg3}"
set-face global LineNumberCursor "%opt{yellow1}"
set-face global LineNumbersWrapped "%opt{bg2}"
set-face global StatusLine "%opt{fg1},%opt{bg2}"
set-face global StatusLineMode "%opt{yellow1}"
set-face global StatusLineInfo "%opt{aqua1}"
set-face global StatusLineValue "%opt{aqua1}"
set-face global StatusCursor "%opt{bg2},%opt{blue1}+b"
set-face global Prompt "%opt{fg1},%opt{bg2}"
set-face global PrimarySelection ",%opt{bg3}"
set-face global SecondarySelection ",%opt{bg2}"
set-face global PrimaryCursor "%opt{bg1},%opt{fg3}"
set-face global SecondaryCursor "%opt{bg1},%opt{bg2}"
set-face global PrimaryCursorEol "%opt{bg1},%opt{orange1}"
set-face global SecondaryCursorEol "%opt{bg1},%opt{orange1}"
set-face global MenuBackground "%opt{fg1},%opt{bg2}"
set-face global MenuForeground "%opt{bg2},%opt{blue1}+b"
set-face global MenuInfo "%opt{fg1},%opt{bg2}"
set-face global InlineInformation "%opt{gray}"
set-face global InlayHint "%opt{gray}+f"
set-face global Error "%opt{red1}"
set-face global DiagnosticError ",,%opt{red1}+c"
set-face global DiagnosticWarning ",,%opt{yellow1}+c"
set-face global MatchingChar "%opt{fg3},%opt{bg3}"
set-face global Whitespace "%opt{bg2}+f"
set-face global Search ",%opt{bg2}"
set-face global WrapMarker "%opt{bg2}"
set-face global Information "%opt{fg1},%opt{bg1}"
set-face global hop_label_head "%opt{purple0}+bf"
set-face global hop_label_tail "%opt{purple0}+bf"
set-face global type "%opt{yellow1}"
set-face global variable "%opt{fg1}"
set-face global function "%opt{green1}"
set-face global string "%opt{green1}"
set-face global keyword "%opt{red1}"
set-face global operator "%opt{purple1}"
set-face global attribute "%opt{aqua1}+i"
set-face global comment "%opt{gray}+i"
set-face global documentation "%opt{gray}+i"
set-face global meta "%opt{purple0}"
set-face global builtin "%opt{orange1}+i"
set-face global InfoDefault "%opt{fg1},%opt{bg1}"
set-face global InfoBlock "%opt{red1}"
set-face global InfoBlockQuote "%opt{red1}"
set-face global InfoHeader "%opt{aqua1}"
set-face global InfoLink "%opt{green1}"
set-face global InfoMono "%opt{red1}"
set-face global InfoRule ",%opt{bg1}"
set-face global InfoDiagnosticError ",,%opt{red1}+c"
set-face global InfoDiagnosticHint ",,%opt{blue1}+c"
set-face global InfoDiagnosticInformation ",,%opt{aqua1}+c"
set-face global InfoDiagnosticWarning ",,%opt{yellow1}+c"
set-face global Reference "%opt{fg3},%opt{bg3}"
set-face global InlayCodeLens "%opt{gray}"
set-face global LineFlagError "%opt{red1}"
set-face global LineFlagHint "%opt{blue1}"
set-face global LineFlagInfo "%opt{aqua1}"
set-face global LineFlagWarning "%opt{yellow1}"
set-face global title "%opt{aqua1}"
set-face global header "%opt{aqua1}"
set-face global mono "%opt{red1}"
set-face global block "%opt{red1}"
set-face global link "%opt{green1}"
set-face global ts_annotation "%opt{fg1}"
set-face global ts_attribute "%opt{aqua1}+i"
set-face global ts_comment "%opt{gray}+i"
set-face global ts_constant "%opt{purple1}"
set-face global ts_constant_character "%opt{aqua1}"
set-face global ts_constant_character_escape "%opt{orange1}"
set-face global ts_constant_macro "%opt{aqua1}"
set-face global ts_constructor "%opt{purple1}"
set-face global ts_definition ",,%opt{aqua1}"
set-face global ts_diagnostic ",,%opt{orange1}+c"
set-face global ts_diagnostic_deprecated "+s"
set-face global ts_diagnostic_error ",,%opt{red1}+c"
set-face global ts_diagnostic_hint ",,%opt{blue1}+c"
set-face global ts_diagnostic_info ",,%opt{aqua1}+c"
set-face global ts_diagnostic_warning ",,%opt{yellow1}+c"
set-face global ts_error "%opt{red1}"
set-face global ts_hint "%opt{blue1}"
set-face global ts_info "%opt{aqua1}"
set-face global ts_warning "%opt{yellow1}"
set-face global ts_diff_delta "%opt{yellow1}"
set-face global ts_diff_minus "%opt{red1}"
set-face global ts_diff_plus "%opt{green1}"
set-face global ts_function "%opt{green1}"
set-face global ts_function_builtin "%opt{yellow1}"
set-face global ts_function_macro "%opt{blue1}"
set-face global ts_keyword "%opt{red1}"
set-face global ts_keyword_control_import "%opt{aqua1}"
set-face global ts_label "%opt{red1}"
set-face global ts_markup_bold "+b"
set-face global ts_markup_heading "%opt{aqua1}"
set-face global ts_markup_italic "+i"
set-face global ts_markup_link_text "%opt{red1}"
set-face global ts_markup_link_url "%opt{green1}"
set-face global ts_markup_raw "%opt{red1}"
set-face global ts_markup_strikethrough "+s"
set-face global ts_module "%opt{aqua1}"
set-face global ts_namespace "%opt{fg1}"
set-face global ts_operator "%opt{purple1}"
set-face global ts_punctuation "%opt{orange1}"
set-face global ts_special "%opt{purple0}"
set-face global ts_string "%opt{green1}"
set-face global ts_string_regexp "%opt{orange1}"
set-face global ts_string_special "%opt{orange1}"
set-face global ts_string_symbol "%opt{yellow1}"
set-face global ts_tag "%opt{aqua1}"
set-face global ts_type "%opt{yellow1}"
set-face global ts_type_enum_variant "+i"
set-face global ts_variable "%opt{fg1}"
set-face global ts_variable_builtin "%opt{orange1}+i"
set-face global ts_variable_other_member "%opt{blue1}"
set-face global ts_variable_parameter "%opt{blue1}+i"

# Missing faces (with fallbacks)
set-face global BufferPadding Default
set-face global value Default
set-face global module Default
set-face global bullet Default
set-face global list Default
set-face global ts_variable_parameter_builtin ts_variable_parameter
set-face global ts_variable_member ts_variable
set-face global ts_variable_other_member_private ts_variable_other_member
set-face global ts_constant_builtin ts_constant
set-face global ts_constant_builtin_boolean ts_constant
set-face global ts_constant_numeric ts_constant
set-face global ts_constant_integer ts_constant
set-face global ts_constant_float ts_constant
set-face global ts_module_builtin ts_module
set-face global ts_string_documentation ts_string
set-face global ts_string_escape ts_string
set-face global ts_string_special_symbol ts_string_special
set-face global ts_string_special_url ts_string_special
set-face global ts_string_special_path ts_string_special
set-face global ts_character Default
set-face global ts_character_special Default
set-face global ts_boolean Default
set-face global ts_number Default
set-face global ts_number_float Default
set-face global ts_type_builtin ts_type
set-face global ts_type_definition ts_type
set-face global ts_type_parameter ts_type
set-face global ts_type_enum ts_type
set-face global ts_attribute_builtin ts_attribute
set-face global ts_property Default
set-face global ts_function_call ts_function
set-face global ts_function_method ts_function
set-face global ts_function_method_call ts_function
set-face global ts_function_method_private ts_function
set-face global ts_function_special ts_function
set-face global ts_keyword_coroutine ts_keyword
set-face global ts_keyword_function ts_keyword
set-face global ts_keyword_operator ts_keyword
set-face global ts_keyword_import ts_keyword
set-face global ts_keyword_type ts_keyword
set-face global ts_keyword_modifier ts_keyword
set-face global ts_keyword_repeat ts_keyword
set-face global ts_keyword_return ts_keyword
set-face global ts_keyword_debug ts_keyword
set-face global ts_keyword_exception ts_keyword
set-face global ts_keyword_conditional ts_keyword
set-face global ts_keyword_conditional_ternary ts_keyword
set-face global ts_keyword_directive ts_keyword
set-face global ts_keyword_directive_define ts_keyword
set-face global ts_keyword_storage ts_keyword
set-face global ts_keyword_storage_type ts_keyword
set-face global ts_keyword_storage_modifier ts_keyword
set-face global ts_keyword_control_conditional ts_keyword
set-face global ts_keyword_control_repeat ts_keyword
set-face global ts_keyword_control_return ts_keyword
set-face global ts_keyword_control_exception ts_keyword
set-face global ts_punctuation_delimiter ts_punctuation
set-face global ts_punctuation_bracket ts_punctuation
set-face global ts_punctuation_special ts_punctuation
set-face global ts_comment_line ts_comment
set-face global ts_comment_line_documentation ts_comment
set-face global ts_comment_block ts_comment
set-face global ts_comment_block_documentation ts_comment
set-face global ts_comment_unused ts_comment
set-face global ts_comment_documentation ts_comment
set-face global ts_comment_error ts_comment
set-face global ts_comment_warning ts_comment
set-face global ts_comment_todo ts_comment
set-face global ts_comment_note ts_comment
set-face global ts_markup Default
set-face global ts_markup_strong Default
set-face global ts_markup_underline Default
set-face global ts_markup_heading_marker ts_markup_heading
set-face global ts_markup_heading_1 ts_markup_heading
set-face global ts_markup_heading_2 ts_markup_heading
set-face global ts_markup_heading_3 ts_markup_heading
set-face global ts_markup_heading_4 ts_markup_heading
set-face global ts_markup_heading_5 ts_markup_heading
set-face global ts_markup_heading_6 ts_markup_heading
set-face global ts_markup_quote Default
set-face global ts_markup_math Default
set-face global ts_markup_link Default
set-face global ts_markup_link_label Default
set-face global ts_markup_raw_block ts_markup_raw
set-face global ts_markup_raw_inline ts_markup_raw
set-face global ts_markup_list Default
set-face global ts_markup_list_checked Default
set-face global ts_markup_list_unchecked Default
set-face global ts_markup_list_unnumbered Default
set-face global ts_markup_list_numbered Default
set-face global ts_diff Default
set-face global ts_diff_plus_gutter ts_diff_plus
set-face global ts_diff_minus_gutter ts_diff_minus
set-face global ts_diff_delta_moved ts_diff_delta
set-face global ts_diff_delta_conflict ts_diff_delta
set-face global ts_diff_delta_gutter ts_diff_delta
set-face global ts_tag_builtin ts_tag
set-face global ts_tag_attribute ts_tag
set-face global ts_tag_delimiter ts_tag
set-face global ts_none Default
set-face global ts_conceal Default
set-face global ts_spell Default
set-face global ts_nospell Default
set-face global ts_embedded Default
