# kanagawa
# Converted from Helix theme

# Palette
declare-option str oldWhite 'rgb:C8C093'
declare-option str fujiWhite 'rgb:DCD7BA'
declare-option str fujiGray 'rgb:727169'
declare-option str sumiInk0 'rgb:16161D'
declare-option str sumiInk1 'rgb:181820'
declare-option str sumiInk2 'rgb:1A1A22'
declare-option str sumiInk3 'rgb:1F1F28'
declare-option str sumiInk4 'rgb:2A2A37'
declare-option str sumiInk5 'rgb:363646'
declare-option str sumiInk6 'rgb:54546D'
declare-option str waveBlue1 'rgb:223249'
declare-option str waveBlue2 'rgb:2D4F67'
declare-option str winterGreen 'rgb:2B3328'
declare-option str winterYellow 'rgb:49443C'
declare-option str winterRed 'rgb:43242B'
declare-option str winterBlue 'rgb:252535'
declare-option str autumnGreen 'rgb:76946A'
declare-option str autumnRed 'rgb:C34043'
declare-option str autumnYellow 'rgb:DCA561'
declare-option str samuraiRed 'rgb:E82424'
declare-option str roninYellow 'rgb:FF9E3B'
declare-option str waveAqua1 'rgb:6A9589'
declare-option str dragonBlue 'rgb:658594'
declare-option str oniViolet 'rgb:957FB8'
declare-option str oniViolet2 'rgb:B8B4D0'
declare-option str crystalBlue 'rgb:7E9CD8'
declare-option str springViolet1 'rgb:938AA9'
declare-option str springViolet2 'rgb:9CABCA'
declare-option str springBlue 'rgb:7FB4CA'
declare-option str lightBlue 'rgb:A3D4D5'
declare-option str waveAqua2 'rgb:7AA89F'
declare-option str waveAqua3 'rgb:68AD99'
declare-option str waveAqua4 'rgb:7AA880'
declare-option str waveAqua5 'rgb:6CAF95'
declare-option str springGreen 'rgb:98BB6C'
declare-option str boatYellow1 'rgb:938056'
declare-option str boatYellow2 'rgb:C0A36E'
declare-option str carpYellow 'rgb:E6C384'
declare-option str sakuraPink 'rgb:D27E99'
declare-option str waveRed 'rgb:E46876'
declare-option str peachRed 'rgb:FF5D62'
declare-option str surimiOrange 'rgb:FFA066'
declare-option str katanaGray 'rgb:717C7C'

# Faces
set-face global Default "%opt{fujiWhite}"
set-face global LineNumbers "%opt{sumiInk6}"
set-face global LineNumberCursor "%opt{roninYellow}+b"
set-face global StatusLine "%opt{oldWhite},%opt{sumiInk0}"
set-face global StatusLineMode "%opt{roninYellow}"
set-face global StatusLineInfo "%opt{dragonBlue}"
set-face global StatusLineValue "%opt{dragonBlue}"
set-face global StatusCursor "%opt{fujiWhite},%opt{waveBlue2}+b"
set-face global Prompt "%opt{oldWhite},%opt{sumiInk0}"
set-face global PrimarySelection ",%opt{waveBlue2}"
set-face global SecondarySelection ",%opt{waveBlue2}"
set-face global PrimaryCursor "%opt{waveBlue1},%opt{fujiWhite}"
set-face global SecondaryCursor "%opt{waveBlue1},%opt{waveAqua2}"
set-face global PrimaryCursorEol "%opt{waveBlue1},%opt{waveAqua2}"
set-face global SecondaryCursorEol "%opt{waveBlue1},%opt{waveAqua2}"
set-face global MenuBackground "%opt{fujiWhite},%opt{waveBlue1}"
set-face global MenuForeground "%opt{fujiWhite},%opt{waveBlue2}+b"
set-face global MenuInfo "%opt{fujiWhite},%opt{waveBlue1}"
set-face global InlineInformation "%opt{sumiInk6}"
set-face global InlayHint "%opt{sumiInk6}"
set-face global Error "%opt{samuraiRed}"
set-face global DiagnosticError ",,%opt{samuraiRed}+c"
set-face global DiagnosticWarning ",,%opt{roninYellow}+c"
set-face global MatchingChar "%opt{waveRed}+b"
set-face global Whitespace "%opt{fujiGray}+f"
set-face global Search ",%opt{waveBlue2}"
set-face global WrapMarker "%opt{sumiInk6}"
set-face global Information "%opt{fujiWhite},%opt{sumiInk0}"
set-face global hop_label_head "%opt{peachRed}+bf"
set-face global hop_label_tail "%opt{peachRed}+bf"
set-face global value "%opt{springBlue}"
set-face global type "%opt{waveAqua2}"
set-face global variable "%opt{fujiWhite}"
set-face global function "%opt{crystalBlue}"
set-face global string "%opt{springGreen}"
set-face global keyword "%opt{oniViolet}+i"
set-face global operator "%opt{boatYellow2}"
set-face global attribute "%opt{waveRed}"
set-face global comment "%opt{fujiGray}"
set-face global documentation "%opt{fujiGray}"
set-face global meta "%opt{peachRed}"
set-face global builtin "%opt{waveRed}"
set-face global InfoDefault "%opt{fujiWhite},%opt{sumiInk0}"
set-face global InfoBlock "%opt{springGreen}"
set-face global InfoBlockQuote "%opt{oniViolet2}"
set-face global InfoBullet "%opt{sakuraPink}"
set-face global InfoHeader "%opt{carpYellow}+b"
set-face global InfoLink "%opt{lightBlue}"
set-face global InfoLinkMono "%opt{surimiOrange}"
set-face global InfoMono "%opt{springGreen}"
set-face global InfoRule ",%opt{sumiInk4}"
set-face global InfoDiagnosticError ",,%opt{samuraiRed}+c"
set-face global InfoDiagnosticHint ",,%opt{waveAqua1}+c"
set-face global InfoDiagnosticInformation ",,%opt{dragonBlue}+c"
set-face global InfoDiagnosticWarning ",,%opt{roninYellow}+c"
set-face global Reference "%opt{waveRed}+b"
set-face global InlayCodeLens "%opt{sumiInk6}"
set-face global LineFlagError "%opt{samuraiRed}"
set-face global LineFlagHint "%opt{waveAqua1}"
set-face global LineFlagInfo "%opt{dragonBlue}"
set-face global LineFlagWarning "%opt{roninYellow}"
set-face global title "%opt{springViolet2}+b"
set-face global header "%opt{carpYellow}+b"
set-face global mono "%opt{springGreen}"
set-face global block "%opt{springGreen}"
set-face global link "%opt{lightBlue}"
set-face global bullet "%opt{sakuraPink}"
set-face global list "%opt{sakuraPink}"
set-face global ts_diagnostic_error ",,%opt{samuraiRed}+c"
set-face global ts_diagnostic_warning ",,%opt{roninYellow}+c"
set-face global ts_diagnostic_info ",,%opt{dragonBlue}+c"
set-face global ts_diagnostic_hint ",,%opt{waveAqua1}+c"
set-face global ts_diagnostic_unnecessary "+d"
set-face global ts_diagnostic_deprecated "+s"
set-face global ts_error "%opt{samuraiRed}"
set-face global ts_warning "%opt{roninYellow}"
set-face global ts_info "%opt{dragonBlue}"
set-face global ts_hint "%opt{waveAqua1}"
set-face global ts_diff_plus "%opt{autumnGreen}"
set-face global ts_diff_minus "%opt{autumnRed}"
set-face global ts_diff_delta "%opt{autumnYellow}"
set-face global ts_attribute "%opt{waveRed}"
set-face global ts_type "%opt{waveAqua2}"
set-face global ts_type_builtin "%opt{springBlue}"
set-face global ts_constructor "%opt{springBlue}"
set-face global ts_constant "%opt{surimiOrange}"
set-face global ts_constant_numeric "%opt{sakuraPink}"
set-face global ts_constant_character_escape "%opt{boatYellow2}+b"
set-face global ts_string "%opt{springGreen}"
set-face global ts_string_regexp "%opt{boatYellow2}"
set-face global ts_string_special_url "%opt{springBlue}"
set-face global ts_string_special_symbol "%opt{oniViolet}"
set-face global ts_comment "%opt{fujiGray}"
set-face global ts_variable "%opt{fujiWhite}"
set-face global ts_variable_builtin "%opt{waveRed}"
set-face global ts_variable_parameter "%opt{oniViolet2}"
set-face global ts_variable_other_member "%opt{carpYellow}"
set-face global ts_label "%opt{springBlue}"
set-face global ts_punctuation "%opt{springViolet2}"
set-face global ts_keyword "%opt{oniViolet}+i"
set-face global ts_keyword_control_return "%opt{peachRed}"
set-face global ts_keyword_control_exception "%opt{peachRed}"
set-face global ts_keyword_directive "%opt{waveRed}"
set-face global ts_operator "%opt{boatYellow2}"
set-face global ts_function "%opt{crystalBlue}"
set-face global ts_function_builtin "%opt{springBlue}"
set-face global ts_function_macro "%opt{waveRed}"
set-face global ts_tag "%opt{waveAqua2}"
set-face global ts_namespace "%opt{surimiOrange}"
set-face global ts_special "%opt{peachRed}"
set-face global ts_markup_heading "%opt{springViolet2}+b"
set-face global ts_markup_heading_marker "%opt{springViolet2}"
set-face global ts_markup_heading_1 "%opt{carpYellow}+b"
set-face global ts_markup_heading_2 "%opt{crystalBlue}+b"
set-face global ts_markup_heading_3 "%opt{waveAqua2}+b"
set-face global ts_markup_list "%opt{sakuraPink}"
set-face global ts_markup_bold "+b"
set-face global ts_markup_italic "+i"
set-face global ts_markup_strikethrough "+s"
set-face global ts_markup_link_text "%opt{springBlue}"
set-face global ts_markup_link_url "%opt{lightBlue}"
set-face global ts_markup_link_label "%opt{surimiOrange}"
set-face global ts_markup_quote "%opt{oniViolet2}"
set-face global ts_markup_raw "%opt{springGreen}"

# Missing faces (with fallbacks)
set-face global LineNumbersWrapped Default
set-face global BufferPadding Default
set-face global module Default
set-face global ts_variable_parameter_builtin ts_variable_parameter
set-face global ts_variable_member ts_variable
set-face global ts_variable_other_member_private ts_variable_other_member
set-face global ts_constant_builtin ts_constant
set-face global ts_constant_builtin_boolean ts_constant
set-face global ts_constant_character ts_constant
set-face global ts_constant_macro ts_constant
set-face global ts_constant_integer ts_constant
set-face global ts_constant_float ts_constant
set-face global ts_module Default
set-face global ts_module_builtin Default
set-face global ts_string_documentation ts_string
set-face global ts_string_escape ts_string
set-face global ts_string_special ts_string
set-face global ts_string_special_path ts_string
set-face global ts_character Default
set-face global ts_character_special Default
set-face global ts_boolean Default
set-face global ts_number Default
set-face global ts_number_float Default
set-face global ts_type_definition ts_type
set-face global ts_type_parameter ts_type
set-face global ts_type_enum ts_type
set-face global ts_type_enum_variant ts_type
set-face global ts_attribute_builtin ts_attribute
set-face global ts_property Default
set-face global ts_function_call ts_function
set-face global ts_function_method ts_function
set-face global ts_function_method_call ts_function
set-face global ts_function_method_private ts_function
set-face global ts_function_special ts_function
set-face global ts_keyword_coroutine ts_keyword
set-face global ts_keyword_function ts_keyword
set-face global ts_keyword_operator ts_keyword
set-face global ts_keyword_import ts_keyword
set-face global ts_keyword_type ts_keyword
set-face global ts_keyword_modifier ts_keyword
set-face global ts_keyword_repeat ts_keyword
set-face global ts_keyword_return ts_keyword
set-face global ts_keyword_debug ts_keyword
set-face global ts_keyword_exception ts_keyword
set-face global ts_keyword_conditional ts_keyword
set-face global ts_keyword_conditional_ternary ts_keyword
set-face global ts_keyword_directive_define ts_keyword_directive
set-face global ts_keyword_storage ts_keyword
set-face global ts_keyword_storage_type ts_keyword
set-face global ts_keyword_storage_modifier ts_keyword
set-face global ts_keyword_control_conditional ts_keyword
set-face global ts_keyword_control_repeat ts_keyword
set-face global ts_keyword_control_import ts_keyword
set-face global ts_punctuation_delimiter ts_punctuation
set-face global ts_punctuation_bracket ts_punctuation
set-face global ts_punctuation_special ts_punctuation
set-face global ts_comment_line ts_comment
set-face global ts_comment_line_documentation ts_comment
set-face global ts_comment_block ts_comment
set-face global ts_comment_block_documentation ts_comment
set-face global ts_comment_unused ts_comment
set-face global ts_comment_documentation ts_comment
set-face global ts_comment_error ts_comment
set-face global ts_comment_warning ts_comment
set-face global ts_comment_todo ts_comment
set-face global ts_comment_note ts_comment
set-face global ts_markup Default
set-face global ts_markup_strong Default
set-face global ts_markup_underline Default
set-face global ts_markup_heading_4 ts_markup_heading
set-face global ts_markup_heading_5 ts_markup_heading
set-face global ts_markup_heading_6 ts_markup_heading
set-face global ts_markup_math Default
set-face global ts_markup_link Default
set-face global ts_markup_raw_block ts_markup_raw
set-face global ts_markup_raw_inline ts_markup_raw
set-face global ts_markup_list_checked ts_markup_list
set-face global ts_markup_list_unchecked ts_markup_list
set-face global ts_markup_list_unnumbered ts_markup_list
set-face global ts_markup_list_numbered ts_markup_list
set-face global ts_diff Default
set-face global ts_diff_plus_gutter ts_diff_plus
set-face global ts_diff_minus_gutter ts_diff_minus
set-face global ts_diff_delta_moved ts_diff_delta
set-face global ts_diff_delta_conflict ts_diff_delta
set-face global ts_diff_delta_gutter ts_diff_delta
set-face global ts_tag_builtin ts_tag
set-face global ts_tag_attribute ts_tag
set-face global ts_tag_delimiter ts_tag
set-face global ts_none Default
set-face global ts_conceal Default
set-face global ts_spell Default
set-face global ts_nospell Default
set-face global ts_embedded Default
