# nord
# Converted from Helix theme

# Palette
declare-option str nord0 'rgb:2e3440'
declare-option str nord1 'rgb:3B4252'
declare-option str nord2 'rgb:434C5E'
declare-option str nord3 'rgb:4C566A'
declare-option str nord3_bright 'rgb:616e88'
declare-option str nord4 'rgb:D8DEE9'
declare-option str nord5 'rgb:E5E9F0'
declare-option str nord6 'rgb:ECEFF4'
declare-option str nord7 'rgb:8FBCBB'
declare-option str nord8 'rgb:88C0D0'
declare-option str nord9 'rgb:81A1C1'
declare-option str nord10 'rgb:5E81AC'
declare-option str nord11 'rgb:BF616A'
declare-option str nord12 'rgb:D08770'
declare-option str nord13 'rgb:EBCB8B'
declare-option str nord14 'rgb:A3BE8C'
declare-option str nord15 'rgb:B48EAD'

# Faces
set-face global Default default
set-face global LineNumbers "%opt{nord3}"
set-face global LineNumberCursor "%opt{nord5}"
set-face global LineNumbersWrapped "%opt{nord3}"
set-face global StatusLine ",%opt{nord1}"
set-face global StatusLineMode "%opt{nord13}"
set-face global StatusLineInfo "%opt{nord8}"
set-face global StatusLineValue "%opt{nord8}"
set-face global StatusCursor "%opt{nord8},%opt{nord2}"
set-face global Prompt ",%opt{nord1}"
set-face global PrimarySelection ",%opt{nord3}"
set-face global SecondarySelection ",%opt{nord3}"
set-face global PrimaryCursor "%opt{nord4}+r"
set-face global SecondaryCursor "%opt{nord4}+r"
set-face global PrimaryCursorEol "%opt{nord4}+r"
set-face global SecondaryCursorEol "%opt{nord4}+r"
set-face global MenuBackground ",%opt{nord1}"
set-face global MenuForeground "%opt{nord8},%opt{nord2}"
set-face global MenuInfo ",%opt{nord1}"
set-face global InlineInformation "%opt{nord3}+i"
set-face global InlayHint "%opt{nord3}+i"
set-face global Error "%opt{nord11}"
set-face global DiagnosticError ",,%opt{nord11}+c"
set-face global DiagnosticWarning ",,%opt{nord13}+c"
set-face global MatchingChar ",%opt{nord3}"
set-face global Whitespace "%opt{nord3}+f"
set-face global Search ",%opt{nord3}"
set-face global WrapMarker "%opt{nord3}"
set-face global Information ",%opt{nord1}"
set-face global hop_label_head "%opt{nord11}+bf"
set-face global hop_label_tail "%opt{nord11}+bf"
set-face global value "%opt{nord7}"
set-face global type "%opt{nord7}"
set-face global variable "%opt{nord4}"
set-face global function "%opt{nord8}"
set-face global string "%opt{nord14}"
set-face global keyword "%opt{nord9}"
set-face global operator "%opt{nord9}"
set-face global attribute "%opt{nord9}"
set-face global comment "%opt{nord3_bright}+i"
set-face global documentation "%opt{nord3_bright}+i"
set-face global meta "%opt{nord9}"
set-face global builtin "%opt{nord9}"
set-face global InfoDefault ",%opt{nord1}"
set-face global InfoBlock "%opt{nord7}"
set-face global InfoBlockQuote "%opt{nord7}"
set-face global InfoBullet "%opt{nord9}"
set-face global InfoHeader "%opt{nord8}"
set-face global InfoMono "%opt{nord7}"
set-face global InfoRule ",%opt{nord1}"
set-face global InfoDiagnosticError ",,%opt{nord11}+c"
set-face global InfoDiagnosticHint ",,%opt{nord10}+c"
set-face global InfoDiagnosticInformation ",,%opt{nord8}+c"
set-face global InfoDiagnosticWarning ",,%opt{nord13}+c"
set-face global Reference ",%opt{nord3}"
set-face global InlayCodeLens "%opt{nord3}+i"
set-face global LineFlagError "%opt{nord11}"
set-face global LineFlagHint "%opt{nord10}"
set-face global LineFlagInfo "%opt{nord8}"
set-face global LineFlagWarning "%opt{nord13}"
set-face global title "%opt{nord8}"
set-face global header "%opt{nord8}"
set-face global mono "%opt{nord7}"
set-face global block "%opt{nord7}"
set-face global bullet "%opt{nord9}"
set-face global list "%opt{nord9}"
set-face global ts_constant "%opt{nord4}"
set-face global ts_constant_builtin "%opt{nord9}"
set-face global ts_constant_builtin_boolean "%opt{nord9}"
set-face global ts_constant_builtin_character "%opt{nord15}"
set-face global ts_constant_character_escape "%opt{nord13}"
set-face global ts_constant_macro "%opt{nord9}"
set-face global ts_constant_numeric "%opt{nord15}"
set-face global ts_constructor "%opt{nord8}"
set-face global ts_diagnostic ",,%opt{nord13}+c"
set-face global ts_diagnostic_error ",,%opt{nord11}+c"
set-face global ts_error "%opt{nord11}"
set-face global ts_diagnostic_hint ",,%opt{nord10}+c"
set-face global ts_hint "%opt{nord10}"
set-face global ts_diagnostic_info ",,%opt{nord8}+c"
set-face global ts_info "%opt{nord8}"
set-face global ts_diagnostic_warning ",,%opt{nord13}+c"
set-face global ts_warning "%opt{nord13}"
set-face global ts_diagnostic_unnecessary "+d"
set-face global ts_diagnostic_deprecated "+s"
set-face global ts_diff_delta "%opt{nord13}"
set-face global ts_diff_minus "%opt{nord11}"
set-face global ts_diff_plus "%opt{nord14}"
set-face global ts_function "%opt{nord8}"
set-face global ts_function_builtin "%opt{nord7}"
set-face global ts_function_method "%opt{nord8}"
set-face global ts_function_macro "%opt{nord9}"
set-face global ts_function_special "%opt{nord9}"
set-face global ts_git_delta_moved "%opt{nord12}"
set-face global ts_keyword "%opt{nord9}"
set-face global ts_keyword_control_conditional "%opt{nord9}"
set-face global ts_keyword_control_exception "%opt{nord9}"
set-face global ts_keyword_control_repeat "%opt{nord9}"
set-face global ts_keyword_directive "%opt{nord9}"
set-face global ts_keyword_function "%opt{nord9}"
set-face global ts_keyword_operator "%opt{nord9}"
set-face global ts_keyword_return "%opt{nord9}"
set-face global ts_keyword_storage_modifier "%opt{nord9}"
set-face global ts_keyword_storage_type "%opt{nord9}"
set-face global ts_punctuation "%opt{nord6}"
set-face global ts_punctuation_bracket "%opt{nord6}"
set-face global ts_punctuation_delimiter "%opt{nord6}"
set-face global ts_punctuation_special "%opt{nord9}"
set-face global ts_string "%opt{nord14}"
set-face global ts_string_escape "%opt{nord13}"
set-face global ts_string_regex "%opt{nord13}"
set-face global ts_string_special "%opt{nord13}"
set-face global ts_type "%opt{nord7}"
set-face global ts_type_builtin "%opt{nord7}"
set-face global ts_variable "%opt{nord4}"
set-face global ts_variable_builtin "%opt{nord9}"
set-face global ts_variable_other_member "%opt{nord4}"
set-face global ts_variable_parameter "%opt{nord8}"
set-face global ts_attribute "%opt{nord9}"
set-face global ts_label "%opt{nord7}"
set-face global ts_namespace "%opt{nord4}"
set-face global ts_operator "%opt{nord9}"
set-face global ts_special "%opt{nord9}"
set-face global ts_tag "%opt{nord7}"
set-face global ts_comment "%opt{nord3_bright}+i"
set-face global ts_markup_heading "%opt{nord8}"
set-face global ts_markup_list "%opt{nord9}"
set-face global ts_markup_bold "+b"
set-face global ts_markup_italic "+i"
set-face global ts_markup_strikethrough "+s"
set-face global ts_markup_link_text "%opt{nord8}"
set-face global ts_markup_raw "%opt{nord7}"

# Missing faces (with fallbacks)
set-face global BufferPadding Default
set-face global module Default
set-face global link Default
set-face global ts_variable_parameter_builtin ts_variable_parameter
set-face global ts_variable_member ts_variable
set-face global ts_variable_other_member_private ts_variable_other_member
set-face global ts_constant_character ts_constant
set-face global ts_constant_integer ts_constant
set-face global ts_constant_float ts_constant
set-face global ts_module Default
set-face global ts_module_builtin Default
set-face global ts_string_documentation ts_string
set-face global ts_string_regexp ts_string
set-face global ts_string_special_symbol ts_string_special
set-face global ts_string_special_url ts_string_special
set-face global ts_string_special_path ts_string_special
set-face global ts_character Default
set-face global ts_character_special Default
set-face global ts_boolean Default
set-face global ts_number Default
set-face global ts_number_float Default
set-face global ts_type_definition ts_type
set-face global ts_type_parameter ts_type
set-face global ts_type_enum ts_type
set-face global ts_type_enum_variant ts_type
set-face global ts_attribute_builtin ts_attribute
set-face global ts_property Default
set-face global ts_function_call ts_function
set-face global ts_function_method_call ts_function_method
set-face global ts_function_method_private ts_function_method
set-face global ts_keyword_coroutine ts_keyword
set-face global ts_keyword_import ts_keyword
set-face global ts_keyword_type ts_keyword
set-face global ts_keyword_modifier ts_keyword
set-face global ts_keyword_repeat ts_keyword
set-face global ts_keyword_debug ts_keyword
set-face global ts_keyword_exception ts_keyword
set-face global ts_keyword_conditional ts_keyword
set-face global ts_keyword_conditional_ternary ts_keyword
set-face global ts_keyword_directive_define ts_keyword_directive
set-face global ts_keyword_storage ts_keyword
set-face global ts_keyword_control_import ts_keyword
set-face global ts_keyword_control_return ts_keyword
set-face global ts_comment_line ts_comment
set-face global ts_comment_line_documentation ts_comment
set-face global ts_comment_block ts_comment
set-face global ts_comment_block_documentation ts_comment
set-face global ts_comment_unused ts_comment
set-face global ts_comment_documentation ts_comment
set-face global ts_comment_error ts_comment
set-face global ts_comment_warning ts_comment
set-face global ts_comment_todo ts_comment
set-face global ts_comment_note ts_comment
set-face global ts_markup Default
set-face global ts_markup_strong Default
set-face global ts_markup_underline Default
set-face global ts_markup_heading_marker ts_markup_heading
set-face global ts_markup_heading_1 ts_markup_heading
set-face global ts_markup_heading_2 ts_markup_heading
set-face global ts_markup_heading_3 ts_markup_heading
set-face global ts_markup_heading_4 ts_markup_heading
set-face global ts_markup_heading_5 ts_markup_heading
set-face global ts_markup_heading_6 ts_markup_heading
set-face global ts_markup_quote Default
set-face global ts_markup_math Default
set-face global ts_markup_link Default
set-face global ts_markup_link_label Default
set-face global ts_markup_link_url Default
set-face global ts_markup_raw_block ts_markup_raw
set-face global ts_markup_raw_inline ts_markup_raw
set-face global ts_markup_list_checked ts_markup_list
set-face global ts_markup_list_unchecked ts_markup_list
set-face global ts_markup_list_unnumbered ts_markup_list
set-face global ts_markup_list_numbered ts_markup_list
set-face global ts_diff Default
set-face global ts_diff_plus_gutter ts_diff_plus
set-face global ts_diff_minus_gutter ts_diff_minus
set-face global ts_diff_delta_moved ts_diff_delta
set-face global ts_diff_delta_conflict ts_diff_delta
set-face global ts_diff_delta_gutter ts_diff_delta
set-face global ts_tag_builtin ts_tag
set-face global ts_tag_attribute ts_tag
set-face global ts_tag_delimiter ts_tag
set-face global ts_none Default
set-face global ts_conceal Default
set-face global ts_spell Default
set-face global ts_nospell Default
set-face global ts_embedded Default
