# poimandres
# Converted from Helix theme

# Palette
declare-option str brightYellow 'rgb:fffac2'
declare-option str brightMint 'rgb:5DE4c7'
declare-option str lowerMint 'rgb:5fb3a1'
declare-option str blueishGreen 'rgb:42675A'
declare-option str lowerBlue 'rgb:89ddff'
declare-option str lightBlue 'rgb:ADD7FF'
declare-option str desaturatedBlue 'rgb:91B4D5'
declare-option str bluishGrayBrighter 'rgb:7390AA'
declare-option str hotRed 'rgb:d0679d'
declare-option str pink 'rgb:f087bd'
declare-option str gray 'rgb:a6accd'
declare-option str gray_c0 'rgb:98a0c2'
declare-option str darkerGray 'rgb:767c9d'
declare-option str darkerGray_50 'rgb:404559'
declare-option str darkerGray_b0 'rgb:6c7494'
declare-option str bluishGray 'rgb:506477'
declare-option str focus 'rgb:303340'
declare-option str bg 'rgb:1b1e28'
declare-option str offWhite 'rgb:e4f0fb'
declare-option str selection 'rgb:30354a'
declare-option str white 'rgb:ffffff'
declare-option str black 'rgb:000000'
declare-option str transparent 'rgb:00000000'

# Faces
set-face global Default ",%opt{bg}"
set-face global LineNumbers "%opt{darkerGray_50}"
set-face global LineNumberCursor "%opt{offWhite}"
set-face global StatusLine ",%opt{bg}"
set-face global StatusLineMode "%opt{bg},%opt{brightMint}+b"
set-face global StatusLineInfo "%opt{gray}"
set-face global StatusLineValue "%opt{bg},%opt{hotRed}+b"
set-face global StatusCursor "%opt{bg},%opt{gray}"
set-face global Prompt "%opt{offWhite},%opt{selection}"
set-face global PrimarySelection ",%opt{selection}"
set-face global SecondarySelection ",%opt{focus}"
set-face global PrimaryCursor "%opt{bg},%opt{gray}"
set-face global SecondaryCursor "%opt{bg},%opt{gray}"
set-face global PrimaryCursorEol "%opt{bg},%opt{gray}"
set-face global SecondaryCursorEol "%opt{bg},%opt{gray}"
set-face global MenuBackground "%opt{offWhite},%opt{bg}"
set-face global MenuForeground "%opt{bg},%opt{gray}"
set-face global MenuInfo "%opt{offWhite},%opt{bg}"
set-face global InlineInformation "%opt{darkerGray_b0}"
set-face global Error "%opt{hotRed}"
set-face global DiagnosticError ",,%opt{hotRed}+c"
set-face global DiagnosticWarning ",,%opt{brightYellow}+c"
set-face global MatchingChar ",%opt{focus}"
set-face global Whitespace "%opt{darkerGray_b0}+i"
set-face global Search ",%opt{focus}"
set-face global WrapMarker "%opt{darkerGray_b0}"
set-face global BufferPadding "%opt{darkerGray_50}"
set-face global hop_label_head ",%opt{focus}"
set-face global hop_label_tail ",%opt{selection}"
set-face global value "%opt{desaturatedBlue}"
set-face global type "%opt{gray_c0}"
set-face global variable "%opt{offWhite}"
set-face global function "%opt{lightBlue}"
set-face global string "%opt{brightMint}"
set-face global keyword "%opt{brightMint}"
set-face global operator "%opt{desaturatedBlue}"
set-face global attribute "%opt{desaturatedBlue}+i"
set-face global comment "%opt{darkerGray_b0}+i"
set-face global documentation "%opt{darkerGray_b0}+i"
set-face global meta "%opt{desaturatedBlue}"
set-face global builtin "%opt{lightBlue}+i"
set-face global InfoBlock "%opt{lightBlue}"
set-face global InfoBlockQuote "%opt{lightBlue}"
set-face global InfoHeader "%opt{brightMint}"
set-face global InfoLink "%opt{lightBlue}"
set-face global InfoMono "%opt{lightBlue}"
set-face global InfoRule ",%opt{selection}"
set-face global InfoDiagnosticError ",,%opt{hotRed}+c"
set-face global InfoDiagnosticHint ",,%opt{lowerMint}+c"
set-face global InfoDiagnosticInformation ",,%opt{lightBlue}+c"
set-face global InfoDiagnosticWarning ",,%opt{brightYellow}+c"
set-face global Reference ",%opt{focus}"
set-face global InlayHint "%opt{darkerGray}"
set-face global InlayCodeLens "%opt{darkerGray}"
set-face global LineFlagError "%opt{hotRed}"
set-face global LineFlagHint "%opt{lowerMint}"
set-face global LineFlagInfo "%opt{lightBlue}"
set-face global LineFlagWarning "%opt{brightYellow}"
set-face global title "%opt{brightMint}"
set-face global header "%opt{brightMint}"
set-face global mono "%opt{lightBlue}"
set-face global block "%opt{lightBlue}"
set-face global link "%opt{lightBlue}"
set-face global ts_attribute "%opt{desaturatedBlue}+i"
set-face global ts_keyword "%opt{brightMint}"
set-face global ts_keyword_directive "%opt{gray}"
set-face global ts_keyword_storage_type "%opt{desaturatedBlue}"
set-face global ts_keyword_storage_modifier "%opt{lowerMint}"
set-face global ts_keyword_other "%opt{brightMint}"
set-face global ts_keyword_operator "%opt{desaturatedBlue}"
set-face global ts_namespace "%opt{lightBlue}"
set-face global ts_punctuation "%opt{gray}"
set-face global ts_punctuation_bracket "%opt{desaturatedBlue}"
set-face global ts_operator "%opt{desaturatedBlue}"
set-face global ts_special "%opt{desaturatedBlue}"
set-face global ts_variable "%opt{offWhite}"
set-face global ts_variable_parameter "%opt{offWhite}"
set-face global ts_variable_builtin "%opt{lightBlue}+i"
set-face global ts_variable_other "%opt{offWhite}"
set-face global ts_type "%opt{gray_c0}"
set-face global ts_type_builtin "%opt{desaturatedBlue}"
set-face global ts_constructor "%opt{lightBlue}"
set-face global ts_function "%opt{lightBlue}"
set-face global ts_function_method "%opt{lightBlue}"
set-face global ts_tag "%opt{brightMint}"
set-face global ts_comment "%opt{darkerGray_b0}+i"
set-face global ts_constant "%opt{brightMint}"
set-face global ts_constant_character_escape "%opt{offWhite}"
set-face global ts_constant_numeric "%opt{brightMint}"
set-face global ts_constant_builtin "%opt{hotRed}"
set-face global ts_label "%opt{gray_c0}"
set-face global ts_string "%opt{brightMint}"
set-face global ts_markup_heading "%opt{brightMint}"
set-face global ts_markup_bold "%opt{bluishGrayBrighter}+b"
set-face global ts_markup_italic "%opt{bluishGrayBrighter}+i"
set-face global ts_markup_strikethrough "+i"
set-face global ts_markup_link_url "%opt{lightBlue}"
set-face global ts_markup_link_text "%opt{lightBlue}"
set-face global ts_markup_raw "%opt{lightBlue}"
set-face global ts_diagnostic_hint ",,%opt{lowerMint}+c"
set-face global ts_diagnostic_info ",,%opt{lightBlue}+c"
set-face global ts_diagnostic_warning ",,%opt{brightYellow}+c"
set-face global ts_diagnostic_error ",,%opt{hotRed}+c"
set-face global ts_diagnostic_unnecessary "+d"
set-face global ts_diagnostic_deprecated "+s"
set-face global ts_hint "%opt{lowerMint}"
set-face global ts_info "%opt{lightBlue}"
set-face global ts_warning "%opt{brightYellow}"
set-face global ts_error "%opt{hotRed}"
set-face global ts_diff_plus "%opt{lowerMint}"
set-face global ts_diff_minus "%opt{hotRed}"
set-face global ts_diff_delta "%opt{lightBlue}"

# Missing faces (with fallbacks)
set-face global LineNumbersWrapped Default
set-face global Information Default
set-face global module Default
set-face global bullet Default
set-face global list Default
set-face global ts_variable_parameter_builtin ts_variable_parameter
set-face global ts_variable_member ts_variable
set-face global ts_variable_other_member ts_variable_other
set-face global ts_variable_other_member_private ts_variable_other
set-face global ts_constant_builtin_boolean ts_constant_builtin
set-face global ts_constant_character ts_constant
set-face global ts_constant_macro ts_constant
set-face global ts_constant_integer ts_constant
set-face global ts_constant_float ts_constant
set-face global ts_module Default
set-face global ts_module_builtin Default
set-face global ts_string_documentation ts_string
set-face global ts_string_regexp ts_string
set-face global ts_string_escape ts_string
set-face global ts_string_special ts_string
set-face global ts_string_special_symbol ts_string
set-face global ts_string_special_url ts_string
set-face global ts_string_special_path ts_string
set-face global ts_character Default
set-face global ts_character_special Default
set-face global ts_boolean Default
set-face global ts_number Default
set-face global ts_number_float Default
set-face global ts_type_definition ts_type
set-face global ts_type_parameter ts_type
set-face global ts_type_enum ts_type
set-face global ts_type_enum_variant ts_type
set-face global ts_attribute_builtin ts_attribute
set-face global ts_property Default
set-face global ts_function_builtin ts_function
set-face global ts_function_call ts_function
set-face global ts_function_macro ts_function
set-face global ts_function_method_call ts_function_method
set-face global ts_function_method_private ts_function_method
set-face global ts_function_special ts_function
set-face global ts_keyword_coroutine ts_keyword
set-face global ts_keyword_function ts_keyword
set-face global ts_keyword_import ts_keyword
set-face global ts_keyword_type ts_keyword
set-face global ts_keyword_modifier ts_keyword
set-face global ts_keyword_repeat ts_keyword
set-face global ts_keyword_return ts_keyword
set-face global ts_keyword_debug ts_keyword
set-face global ts_keyword_exception ts_keyword
set-face global ts_keyword_conditional ts_keyword
set-face global ts_keyword_conditional_ternary ts_keyword
set-face global ts_keyword_directive_define ts_keyword_directive
set-face global ts_keyword_storage ts_keyword
set-face global ts_keyword_control_conditional ts_keyword
set-face global ts_keyword_control_repeat ts_keyword
set-face global ts_keyword_control_import ts_keyword
set-face global ts_keyword_control_return ts_keyword
set-face global ts_keyword_control_exception ts_keyword
set-face global ts_punctuation_delimiter ts_punctuation
set-face global ts_punctuation_special ts_punctuation
set-face global ts_comment_line ts_comment
set-face global ts_comment_line_documentation ts_comment
set-face global ts_comment_block ts_comment
set-face global ts_comment_block_documentation ts_comment
set-face global ts_comment_unused ts_comment
set-face global ts_comment_documentation ts_comment
set-face global ts_comment_error ts_comment
set-face global ts_comment_warning ts_comment
set-face global ts_comment_todo ts_comment
set-face global ts_comment_note ts_comment
set-face global ts_markup Default
set-face global ts_markup_strong Default
set-face global ts_markup_underline Default
set-face global ts_markup_heading_marker ts_markup_heading
set-face global ts_markup_heading_1 ts_markup_heading
set-face global ts_markup_heading_2 ts_markup_heading
set-face global ts_markup_heading_3 ts_markup_heading
set-face global ts_markup_heading_4 ts_markup_heading
set-face global ts_markup_heading_5 ts_markup_heading
set-face global ts_markup_heading_6 ts_markup_heading
set-face global ts_markup_quote Default
set-face global ts_markup_math Default
set-face global ts_markup_link Default
set-face global ts_markup_link_label Default
set-face global ts_markup_raw_block ts_markup_raw
set-face global ts_markup_raw_inline ts_markup_raw
set-face global ts_markup_list Default
set-face global ts_markup_list_checked Default
set-face global ts_markup_list_unchecked Default
set-face global ts_markup_list_unnumbered Default
set-face global ts_markup_list_numbered Default
set-face global ts_diff Default
set-face global ts_diff_plus_gutter ts_diff_plus
set-face global ts_diff_minus_gutter ts_diff_minus
set-face global ts_diff_delta_moved ts_diff_delta
set-face global ts_diff_delta_conflict ts_diff_delta
set-face global ts_diff_delta_gutter ts_diff_delta
set-face global ts_tag_builtin ts_tag
set-face global ts_tag_attribute ts_tag
set-face global ts_tag_delimiter ts_tag
set-face global ts_none Default
set-face global ts_conceal Default
set-face global ts_spell Default
set-face global ts_nospell Default
set-face global ts_embedded Default
