# tokyonight_storm
# Converted from Helix theme

# Palette
declare-option str red 'rgb:f7768e'
declare-option str orange 'rgb:ff9e64'
declare-option str yellow 'rgb:e0af68'
declare-option str light_green 'rgb:9ece6a'
declare-option str green 'rgb:73daca'
declare-option str aqua 'rgb:2ac3de'
declare-option str teal 'rgb:1abc9c'
declare-option str turquoise 'rgb:89ddff'
declare-option str light_cyan 'rgb:b4f9f8'
declare-option str cyan 'rgb:7dcfff'
declare-option str blue 'rgb:7aa2f7'
declare-option str purple 'rgb:9d7cd8'
declare-option str magenta 'rgb:bb9af7'
declare-option str comment 'rgb:565f89'
declare-option str black 'rgb:414868'
declare-option str add 'rgb:449dab'
declare-option str change 'rgb:6183bb'
declare-option str delete 'rgb:914c54'
declare-option str error 'rgb:db4b4b'
declare-option str info 'rgb:0db9d7'
declare-option str hint 'rgb:1abc9c'
declare-option str fg 'rgb:c0caf5'
declare-option str fg_dark 'rgb:a9b1d6'
declare-option str fg_gutter 'rgb:3b4261'
declare-option str fg_linenr 'rgb:737aa2'
declare-option str fg_selected 'rgb:343a55'
declare-option str border 'rgb:1d202f'
declare-option str border_highlight 'rgb:29a4bd'
declare-option str bg 'rgb:24283b'
declare-option str bg_inlay 'rgb:233745'
declare-option str bg_selection 'rgb:373d5a'
declare-option str bg_menu 'rgb:1f2335'
declare-option str bg_focus 'rgb:2e3c64'

# Faces
set-face global Default "%opt{fg}"
set-face global LineNumbers "%opt{fg_gutter}"
set-face global LineNumberCursor "%opt{fg_linenr}"
set-face global StatusLine "%opt{fg_dark},%opt{bg_menu}"
set-face global StatusLineMode "%opt{yellow}"
set-face global StatusLineInfo "%opt{info}"
set-face global StatusLineValue "%opt{info}"
set-face global StatusCursor ",%opt{fg_selected}"
set-face global Prompt "%opt{fg_dark},%opt{bg_menu}"
set-face global PrimarySelection ",%opt{bg_selection}"
set-face global SecondarySelection ",%opt{bg_selection}"
set-face global PrimaryCursor "+r"
set-face global SecondaryCursor "+r"
set-face global PrimaryCursorEol "+r"
set-face global SecondaryCursorEol "+r"
set-face global MenuBackground "%opt{fg},%opt{bg_menu}"
set-face global MenuForeground ",%opt{fg_selected}"
set-face global MenuInfo "%opt{fg},%opt{bg_menu}"
set-face global InlineInformation "%opt{teal},%opt{bg_inlay}"
set-face global InlayHint "%opt{teal},%opt{bg_inlay}+f"
set-face global Error "%opt{error}"
set-face global DiagnosticError ",,%opt{error}+c"
set-face global DiagnosticWarning ",,%opt{yellow}+c"
set-face global MatchingChar "%opt{orange}+b"
set-face global Whitespace "%opt{fg_gutter}+f"
set-face global Search ",%opt{bg_selection}"
set-face global Information "%opt{fg},%opt{bg_menu}"
set-face global hop_label_head "%opt{orange}+bf"
set-face global hop_label_tail "%opt{orange}+bf"
set-face global value "%opt{aqua}"
set-face global type "%opt{aqua}"
set-face global variable "%opt{fg}"
set-face global function "%opt{blue}+i"
set-face global string "%opt{light_green}"
set-face global keyword "%opt{purple}+i"
set-face global operator "%opt{turquoise}"
set-face global attribute "%opt{cyan}"
set-face global comment "%opt{comment}+i"
set-face global documentation "%opt{comment}+i"
set-face global meta "%opt{aqua}"
set-face global builtin "%opt{red}"
set-face global InfoDefault "%opt{fg},%opt{bg_menu}"
set-face global InfoBlock "%opt{teal}"
set-face global InfoBlockQuote "%opt{teal}"
set-face global InfoBullet "%opt{orange}+b"
set-face global InfoHeader "%opt{blue}+b"
set-face global InfoLink "+u"
set-face global InfoLinkMono "%opt{teal}"
set-face global InfoMono "%opt{blue},%opt{black}"
set-face global InfoRule ",%opt{fg_gutter}"
set-face global InfoDiagnosticError ",,%opt{error}+c"
set-face global InfoDiagnosticHint ",,%opt{hint}+c"
set-face global InfoDiagnosticInformation ",,%opt{info}+c"
set-face global InfoDiagnosticWarning ",,%opt{yellow}+c"
set-face global Reference "%opt{orange}+b"
set-face global InlayCodeLens "%opt{teal},%opt{bg_inlay}"
set-face global LineFlagError "%opt{error}"
set-face global LineFlagHint "%opt{hint}"
set-face global LineFlagInfo "%opt{info}"
set-face global LineFlagWarning "%opt{yellow}"
set-face global title "%opt{blue}+b"
set-face global header "%opt{blue}+b"
set-face global mono "%opt{blue},%opt{black}"
set-face global block "%opt{teal}"
set-face global link "+u"
set-face global bullet "%opt{orange}+b"
set-face global list "%opt{orange}+b"
set-face global ts_attribute "%opt{cyan}"
set-face global ts_comment "%opt{comment}+i"
set-face global ts_comment_block_documentation "%opt{yellow}"
set-face global ts_comment_line_documentation "%opt{yellow}"
set-face global ts_constant "%opt{orange}"
set-face global ts_constant_builtin "%opt{aqua}"
set-face global ts_constant_character "%opt{light_green}"
set-face global ts_constant_character_escape "%opt{magenta}"
set-face global ts_constructor "%opt{aqua}"
set-face global ts_function "%opt{blue}+i"
set-face global ts_function_builtin "%opt{aqua}"
set-face global ts_function_macro "%opt{cyan}"
set-face global ts_function_special "%opt{cyan}"
set-face global ts_keyword "%opt{purple}+i"
set-face global ts_keyword_control "%opt{magenta}"
set-face global ts_keyword_control_import "%opt{cyan}"
set-face global ts_keyword_control_return "%opt{purple}+i"
set-face global ts_keyword_directive "%opt{cyan}"
set-face global ts_keyword_function "%opt{magenta}"
set-face global ts_keyword_operator "%opt{magenta}"
set-face global ts_label "%opt{blue}"
set-face global ts_namespace "%opt{cyan}"
set-face global ts_operator "%opt{turquoise}"
set-face global ts_punctuation "%opt{turquoise}"
set-face global ts_special "%opt{aqua}"
set-face global ts_string "%opt{light_green}"
set-face global ts_string_regexp "%opt{light_cyan}"
set-face global ts_string_special "%opt{aqua}"
set-face global ts_tag "%opt{magenta}"
set-face global ts_type "%opt{aqua}"
set-face global ts_type_builtin "%opt{aqua}"
set-face global ts_type_enum_variant "%opt{orange}"
set-face global ts_variable "%opt{fg}"
set-face global ts_variable_builtin "%opt{red}"
set-face global ts_variable_other_member "%opt{green}"
set-face global ts_variable_parameter "%opt{yellow}+i"
set-face global ts_markup_bold "+b"
set-face global ts_markup_heading "%opt{blue}+b"
set-face global ts_markup_heading_completion "%opt{fg},%opt{bg_menu}"
set-face global ts_markup_heading_hover ",%opt{fg_selected}"
set-face global ts_markup_italic "+i"
set-face global ts_markup_link "%opt{blue}+u"
set-face global ts_markup_link_label "%opt{teal}"
set-face global ts_markup_link_text "%opt{teal}"
set-face global ts_markup_link_url "+u"
set-face global ts_markup_list "%opt{orange}+b"
set-face global ts_markup_normal_completion "%opt{comment}"
set-face global ts_markup_normal_hover "%opt{fg_dark}"
set-face global ts_markup_raw "%opt{teal}"
set-face global ts_markup_raw_inline "%opt{blue},%opt{black}"
set-face global ts_markup_strikethrough "+s"
set-face global ts_diff_delta "%opt{change}"
set-face global ts_diff_delta_moved "%opt{blue}"
set-face global ts_diff_minus "%opt{delete}"
set-face global ts_diff_plus "%opt{add}"
set-face global ts_error "%opt{error}"
set-face global ts_warning "%opt{yellow}"
set-face global ts_info "%opt{info}"
set-face global ts_hint "%opt{hint}"
set-face global ts_diagnostic_error ",,%opt{error}+c"
set-face global ts_diagnostic_warning ",,%opt{yellow}+c"
set-face global ts_diagnostic_info ",,%opt{info}+c"
set-face global ts_diagnostic_hint ",,%opt{hint}+c"
set-face global ts_diagnostic_unnecessary "+d"
set-face global ts_diagnostic_deprecated "+s"

# Missing faces (with fallbacks)
set-face global LineNumbersWrapped Default
set-face global WrapMarker Default
set-face global BufferPadding Default
set-face global module Default
set-face global ts_variable_parameter_builtin ts_variable_parameter
set-face global ts_variable_member ts_variable
set-face global ts_variable_other_member_private ts_variable_other_member
set-face global ts_constant_builtin_boolean ts_constant_builtin
set-face global ts_constant_macro ts_constant
set-face global ts_constant_numeric ts_constant
set-face global ts_constant_integer ts_constant
set-face global ts_constant_float ts_constant
set-face global ts_module Default
set-face global ts_module_builtin Default
set-face global ts_string_documentation ts_string
set-face global ts_string_escape ts_string
set-face global ts_string_special_symbol ts_string_special
set-face global ts_string_special_url ts_string_special
set-face global ts_string_special_path ts_string_special
set-face global ts_character Default
set-face global ts_character_special Default
set-face global ts_boolean Default
set-face global ts_number Default
set-face global ts_number_float Default
set-face global ts_type_definition ts_type
set-face global ts_type_parameter ts_type
set-face global ts_type_enum ts_type
set-face global ts_attribute_builtin ts_attribute
set-face global ts_property Default
set-face global ts_function_call ts_function
set-face global ts_function_method ts_function
set-face global ts_function_method_call ts_function
set-face global ts_function_method_private ts_function
set-face global ts_keyword_coroutine ts_keyword
set-face global ts_keyword_import ts_keyword
set-face global ts_keyword_type ts_keyword
set-face global ts_keyword_modifier ts_keyword
set-face global ts_keyword_repeat ts_keyword
set-face global ts_keyword_return ts_keyword
set-face global ts_keyword_debug ts_keyword
set-face global ts_keyword_exception ts_keyword
set-face global ts_keyword_conditional ts_keyword
set-face global ts_keyword_conditional_ternary ts_keyword
set-face global ts_keyword_directive_define ts_keyword_directive
set-face global ts_keyword_storage ts_keyword
set-face global ts_keyword_storage_type ts_keyword
set-face global ts_keyword_storage_modifier ts_keyword
set-face global ts_keyword_control_conditional ts_keyword_control
set-face global ts_keyword_control_repeat ts_keyword_control
set-face global ts_keyword_control_exception ts_keyword_control
set-face global ts_punctuation_delimiter ts_punctuation
set-face global ts_punctuation_bracket ts_punctuation
set-face global ts_punctuation_special ts_punctuation
set-face global ts_comment_line ts_comment
set-face global ts_comment_block ts_comment
set-face global ts_comment_unused ts_comment
set-face global ts_comment_documentation ts_comment
set-face global ts_comment_error ts_comment
set-face global ts_comment_warning ts_comment
set-face global ts_comment_todo ts_comment
set-face global ts_comment_note ts_comment
set-face global ts_markup Default
set-face global ts_markup_strong Default
set-face global ts_markup_underline Default
set-face global ts_markup_heading_marker ts_markup_heading
set-face global ts_markup_heading_1 ts_markup_heading
set-face global ts_markup_heading_2 ts_markup_heading
set-face global ts_markup_heading_3 ts_markup_heading
set-face global ts_markup_heading_4 ts_markup_heading
set-face global ts_markup_heading_5 ts_markup_heading
set-face global ts_markup_heading_6 ts_markup_heading
set-face global ts_markup_quote Default
set-face global ts_markup_math Default
set-face global ts_markup_raw_block ts_markup_raw
set-face global ts_markup_list_checked ts_markup_list
set-face global ts_markup_list_unchecked ts_markup_list
set-face global ts_markup_list_unnumbered ts_markup_list
set-face global ts_markup_list_numbered ts_markup_list
set-face global ts_diff Default
set-face global ts_diff_plus_gutter ts_diff_plus
set-face global ts_diff_minus_gutter ts_diff_minus
set-face global ts_diff_delta_conflict ts_diff_delta
set-face global ts_diff_delta_gutter ts_diff_delta
set-face global ts_tag_builtin ts_tag
set-face global ts_tag_attribute ts_tag
set-face global ts_tag_delimiter ts_tag
set-face global ts_none Default
set-face global ts_conceal Default
set-face global ts_spell Default
set-face global ts_nospell Default
set-face global ts_embedded Default
